// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
// Wie Next.js lokal: zuerst .env, dann .env.local überschreibt — damit `migrate`/`db seed` dieselbe DB nutzen wie `next dev`.
// Ohne .env.local bleibt nur .env wirksam; Shell-Exporte werden von Dateiwerten überschrieben.
loadEnv({ path: ".env", override: true });
loadEnv({ path: ".env.local", override: true });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
